# Generated by Django 3.2.9 on 2021-12-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.CharField(default='', max_length=2000)),
                ('subject', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
