# Generated by Django 2.2.8 on 2021-12-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_vector',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='title_vector',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
